// <auto-generated />
using System;
using BomPriceApproval.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BomPriceApproval.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503042325_ApprovalItem_AllowReMarginLoop")]
    partial class ApprovalItem_AllowReMarginLoop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.AdminAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("AdminUserId")
                        .HasColumnType("integer");

                    b.Property<string>("AfterJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("BeforeJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.HasIndex("AdminUserId", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AdminAuditLogs");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.ApprovalItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("MarginPerKg")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MaterialCostPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("OtherCostPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("ProfitMarginPct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("QuotationApprovalId")
                        .HasColumnType("integer");

                    b.Property<int>("RequisitionItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalesPricePerKgAed")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("SalesPricePerKgForeign")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionItemId");

                    b.HasIndex("QuotationApprovalId", "RequisitionItemId")
                        .IsUnique();

                    b.ToTable("ApprovalItems");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.BomCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BomHeaderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CommissionPerKg")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("FohAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("FohPerKg")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("LandedCostType")
                        .HasColumnType("integer");

                    b.Property<decimal>("LandedCostValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("PrintingCostCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("PrintingCostPerKg")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("RawMaterialCostTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SubmittedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalCostPerKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TransportPerKg")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BomHeaderId")
                        .IsUnique();

                    b.HasIndex("SubmittedByUserId");

                    b.ToTable("BomCosts");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.BomCostLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BomHeaderId")
                        .HasColumnType("integer");

                    b.Property<int>("BomLineId")
                        .HasColumnType("integer");

                    b.Property<decimal>("CostPerKg")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("CostPerKgInAed")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("CostPerKgInQuoteCurrency")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BomHeaderId");

                    b.HasIndex("BomLineId");

                    b.ToTable("BomCostLines");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.BomHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("RequisitionItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalCostPerKg")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RequisitionItemId")
                        .IsUnique();

                    b.ToTable("BomHeaders");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.BomLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BomHeaderId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LastModifiedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Micron")
                        .HasColumnType("text");

                    b.Property<int>("ProcessId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QtyPerKg")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("RawMaterialItemId")
                        .HasColumnType("integer");

                    b.Property<decimal>("WastagePct")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("BomHeaderId");

                    b.HasIndex("LastModifiedByUserId");

                    b.HasIndex("ProcessId");

                    b.HasIndex("RawMaterialItemId");

                    b.ToTable("BomLines", t =>
                        {
                            t.HasCheckConstraint("ck_bom_lines_qty_per_kg_positive", "\"QtyPerKg\" > 0");
                        });
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Fujairah"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Al Ain"
                        });
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.BranchChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamptz")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("NewBranchId")
                        .HasColumnType("integer");

                    b.Property<int>("OldBranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RequisitionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .IsDescending();

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("NewBranchId");

                    b.HasIndex("OldBranchId");

                    b.HasIndex("RequisitionId");

                    b.ToTable("BranchChangeHistories");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.CodeCounter", b =>
                {
                    b.Property<string>("Sequence")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("NextValue")
                        .HasColumnType("integer");

                    b.HasKey("Sequence");

                    b.ToTable("CodeCounters");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.CostingDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BomHeaderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FohAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("LandedCostType")
                        .HasColumnType("integer");

                    b.Property<decimal>("LandedCostValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BomHeaderId")
                        .IsUnique();

                    b.ToTable("CostingDrafts");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SalesPersonId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SalesPersonId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.CustomerChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("NewCustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("OldCustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RequisitionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt")
                        .IsDescending();

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("NewCustomerId");

                    b.HasIndex("OldCustomerId");

                    b.HasIndex("RequisitionId");

                    b.ToTable("CustomerChangeHistories");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("RateToAed")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("SetByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SetByUserId");

                    b.ToTable("ExchangeRates");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("LastPurchasePrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Code", "BranchId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.ItemLastCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerKg")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("ItemLastCosts");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.Process", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Processes");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.QuotationApproval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ApprovedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CostFxSnapshot")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuperseded")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("QuotationRequestId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RateSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("Stage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SupersededAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("QuotationRequestId")
                        .HasDatabaseName("ix_quotation_approvals_current")
                        .HasFilter("\"IsSuperseded\" = false");

                    b.ToTable("QuotationApprovals");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.QuotationRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CancelledByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ExchangeRateSnapshot")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RefNo")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasComputedColumnSql("'REQ-' || LPAD(\"Id\"::text, 6, '0')", true);

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SalesPersonId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SalesPersonId");

                    b.ToTable("QuotationRequests");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.RequisitionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CostingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ExpectedQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<bool>("HasPrinting")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("QuotationRequestId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("QuotationRequestId", "ItemId")
                        .IsUnique();

                    b.ToTable("RequisitionItems", t =>
                        {
                            t.HasCheckConstraint("ck_requisition_items_expected_qty_positive", "\"ExpectedQty\" > 0");
                        });
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.RevokedJti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("RevokedJtis");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.SalesGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SalesGroups");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<byte[]>("SignatureImage")
                        .HasColumnType("bytea");

                    b.Property<string>("SignatureMimeType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.UserBranch", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "BranchId");

                    b.HasIndex("BranchId");

                    b.ToTable("UserBranches");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.AdminAuditLog", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.ApprovalItem", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.QuotationApproval", "QuotationApproval")
                        .WithMany("Items")
                        .HasForeignKey("QuotationApprovalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.RequisitionItem", "RequisitionItem")
                        .WithMany("ApprovalItems")
                        .HasForeignKey("RequisitionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuotationApproval");

                    b.Navigation("RequisitionItem");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.BomCost", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.BomHeader", "BomHeader")
                        .WithOne("Cost")
                        .HasForeignKey("BomPriceApproval.API.Domain.Entities.BomCost", "BomHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BomHeader");

                    b.Navigation("SubmittedBy");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.BomCostLine", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.BomHeader", "BomHeader")
                        .WithMany()
                        .HasForeignKey("BomHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.BomLine", "BomLine")
                        .WithMany()
                        .HasForeignKey("BomLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BomHeader");

                    b.Navigation("BomLine");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.BomHeader", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.RequisitionItem", "RequisitionItem")
                        .WithOne("BomHeader")
                        .HasForeignKey("BomPriceApproval.API.Domain.Entities.BomHeader", "RequisitionItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("RequisitionItem");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.BomLine", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.BomHeader", "BomHeader")
                        .WithMany("Lines")
                        .HasForeignKey("BomHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BomPriceApproval.API.Domain.Entities.Process", "Process")
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.Item", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomHeader");

                    b.Navigation("LastModifiedBy");

                    b.Navigation("Process");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.BranchChangeHistory", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.Branch", "NewBranch")
                        .WithMany()
                        .HasForeignKey("NewBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.Branch", "OldBranch")
                        .WithMany()
                        .HasForeignKey("OldBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.QuotationRequest", "Requisition")
                        .WithMany()
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("NewBranch");

                    b.Navigation("OldBranch");

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.CostingDraft", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.BomHeader", "BomHeader")
                        .WithOne()
                        .HasForeignKey("BomPriceApproval.API.Domain.Entities.CostingDraft", "BomHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomHeader");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.Customer", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.Branch", null)
                        .WithMany("Customers")
                        .HasForeignKey("BranchId");

                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "SalesPerson")
                        .WithMany()
                        .HasForeignKey("SalesPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("SalesPerson");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.CustomerChangeHistory", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.Customer", "NewCustomer")
                        .WithMany()
                        .HasForeignKey("NewCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.Customer", "OldCustomer")
                        .WithMany()
                        .HasForeignKey("OldCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.QuotationRequest", "Requisition")
                        .WithMany()
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("NewCustomer");

                    b.Navigation("OldCustomer");

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.ExchangeRate", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "SetBy")
                        .WithMany()
                        .HasForeignKey("SetByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SetBy");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.Item", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.Branch", "Branch")
                        .WithMany("Items")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.ItemLastCost", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.Item", "Item")
                        .WithOne()
                        .HasForeignKey("BomPriceApproval.API.Domain.Entities.ItemLastCost", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.Notification", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.PushSubscription", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.QuotationApproval", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.QuotationRequest", "QuotationRequest")
                        .WithMany("Approvals")
                        .HasForeignKey("QuotationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("QuotationRequest");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.QuotationRequest", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.Branch", "Branch")
                        .WithMany("QuotationRequests")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "CancelledBy")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BomPriceApproval.API.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "SalesPerson")
                        .WithMany()
                        .HasForeignKey("SalesPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CancelledBy");

                    b.Navigation("Customer");

                    b.Navigation("SalesPerson");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.RequisitionItem", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.QuotationRequest", "QuotationRequest")
                        .WithMany("Items")
                        .HasForeignKey("QuotationRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("QuotationRequest");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.User", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId");

                    b.HasOne("BomPriceApproval.API.Domain.Entities.SalesGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.UserBranch", b =>
                {
                    b.HasOne("BomPriceApproval.API.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BomPriceApproval.API.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.BomHeader", b =>
                {
                    b.Navigation("Cost");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Items");

                    b.Navigation("QuotationRequests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.QuotationApproval", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.QuotationRequest", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.RequisitionItem", b =>
                {
                    b.Navigation("ApprovalItems");

                    b.Navigation("BomHeader");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.SalesGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("BomPriceApproval.API.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
